#db stuff
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookee
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true

  #hibernate stuff
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        format_sql: true
        ddl-auto: none
    generate-ddl: false

  #file stuff
  servlet:
    multipart:
      max-file-size: 20MB

server:
  error:
    include-stacktrace: never

#todo imho, file path must be read from ENV variable
#todo also, test this on deployment (heroku)
file_upload_path: "/home/hamdam/Pictures/bookee/"

jwt:
  secret: secret
  access-token-validity: 3600000
  refresh-token-validity: 1728000000