#db stuff
spring:
  datasource:
    url: jdbc:postgresql://db:5432/bookee
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: true

  #hibernate stuff
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        format_sql: true
        ddl-auto: none
    generate-ddl: false

  #file stuff
  servlet:
    multipart:
      max-file-size: 20MB

server:
  error:
    include-stacktrace: never

jwt:
  secret: secret
  access-token-validity: 3600000
  refresh-token-validity: 1728000000

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    stack:
      auto: false
    region:
      static: eu-central-1

aws:
  s3:
    bucket: bookee-app