package hamdam.bookee.APIs.role;

// TODO: 9/2/22 naming
public enum Permissions {

    GET_BOOK,
    CREATE_BOOK,
    UPDATE_BOOK,
    DELETE_BOOK,

    GET_GENRE,
    CREATE_GENRE,
    UPDATE_GENRE,
    DELETE_GENRE,

    GET_ROLE,
    CREATE_ROLE,
    UPDATE_ROLE,
    DELETE_ROLE,

    GET_USER,
    CREATE_USER,
    UPDATE_USER,
    DELETE_USER,

    GET_ROLE_REQUEST,
    GET_ALL_ROLE_REQUESTS_BY_ADMIN,
    CREATE_ROLE_REQUEST,
    UPDATE_ROLE_REQUEST,
    DELETE_ROLE_REQUEST,
    DELETE_ANY_ROLE_REQUEST_BY_ADMIN,

    USER,
    ADMIN,
    AUTHOR

}
