CREATE TABLE book
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    tagline     VARCHAR(100),
    description VARCHAR(200),
    rating      DOUBLE PRECISION,
    time_stamp  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_book PRIMARY KEY (id)
);

CREATE TABLE book_author
(
    author_id BIGINT NOT NULL,
    book_id   BIGINT NOT NULL
);

CREATE TABLE book_genre
(
    book_id  BIGINT NOT NULL,
    genre_id BIGINT NOT NULL
);

CREATE TABLE genre
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(200),
    time_stamp  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_genre PRIMARY KEY (id)
);

CREATE TABLE image
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image_name VARCHAR(255),
    url        VARCHAR(255)                            NOT NULL,
    time_stamp TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_image PRIMARY KEY (id)
);

CREATE TABLE role
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name  VARCHAR(255)                            NOT NULL,
    is_default BOOLEAN                                 NOT NULL,
    time_stamp TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE role_permissions
(
    role_id BIGINT NOT NULL,
    permissions        VARCHAR(255)
);

CREATE TABLE role_request
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id           BIGINT                                  NOT NULL,
    requested_role_id BIGINT                                  NOT NULL,
    state             VARCHAR(255),
    description       VARCHAR(200),
    time_stamp        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_role_request PRIMARY KEY (id)
);

CREATE TABLE app_user
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    username      VARCHAR(255),
    password      VARCHAR(255),
    role_id       BIGINT,
    user_image_id BIGINT,
    time_stamp    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE book_author
    ADD CONSTRAINT fk_booaut_on_app_user_entity FOREIGN KEY (author_id) REFERENCES app_user (id);

ALTER TABLE book_author
    ADD CONSTRAINT fk_booaut_on_book_entity FOREIGN KEY (book_id) REFERENCES book (id);

ALTER TABLE book_genre
    ADD CONSTRAINT fk_boogen_on_book_entity FOREIGN KEY (book_id) REFERENCES book (id);

ALTER TABLE book_genre
    ADD CONSTRAINT fk_boogen_on_genre_entity FOREIGN KEY (genre_id) REFERENCES genre (id);

ALTER TABLE role
    ADD CONSTRAINT uc_role_rolename UNIQUE (role_name);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_role_permissions_on_app_role_entity FOREIGN KEY (role_id) REFERENCES role (id);

ALTER TABLE role_request
    ADD CONSTRAINT FK_ROLE_REQUEST_ON_REQUESTEDROLE FOREIGN KEY (requested_role_id) REFERENCES role (id);

ALTER TABLE role_request
    ADD CONSTRAINT FK_ROLE_REQUEST_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id);

ALTER TABLE app_user
    ADD CONSTRAINT uc_user_username UNIQUE (username);

ALTER TABLE app_user
    ADD CONSTRAINT FK_USER_ON_ROLE FOREIGN KEY (role_id) REFERENCES role (id);

ALTER TABLE app_user
    ADD CONSTRAINT FK_USER_ON_USERIMAGE FOREIGN KEY (user_image_id) REFERENCES image (id);