INSERT INTO app_role_entity_permissions (app_role_entity_id, permissions)
VALUES (1, 'MONITOR_USER');
VALUES (1, 'MONITOR_ROLE');
VALUES (1, 'MONITOR_ROLE_REQUEST');
VALUES (1, 'GET_BOOK');
VALUES (1, 'CREATE_BOOK');
VALUES (1, 'UPDATE_BOOK');
VALUES (1, 'DELETE_BOOK');
VALUES (1, 'GET_GENRE');
VALUES (1, 'CREATE_GENRE');
VALUES (1, 'UPDATE_GENRE');
VALUES (1, 'DELETE_GENRE');

INSERT INTO app_role_entity_permissions (app_role_entity_id, permissions)
VALUES (2, 'GET_USER');
VALUES (2, 'UPDATE_USER');
VALUES (2, 'DELETE_USER');
VALUES (2, 'GET_BOOK');
VALUES (2, 'CREATE_BOOK');
VALUES (2, 'UPDATE_BOOK');
VALUES (2, 'DELETE_BOOK');
VALUES (2, 'GET_GENRE');
VALUES (2, 'CREATE_GENRE');
VALUES (2, 'UPDATE_GENRE');
VALUES (2, 'DELETE_GENRE');

INSERT INTO app_role_entity_permissions (app_role_entity_id, permissions)
VALUES (3, 'GET_USER');
VALUES (3, 'UPDATE_USER');
VALUES (3, 'DELETE_USER');
VALUES (3, 'GET_ROLE_REQUEST');
VALUES (3, 'CREATE_ROLE_REQUEST');
VALUES (3, 'UPDATE_ROLE_REQUEST');
VALUES (3, 'DELETE_ROLE_REQUEST');
VALUES (3, 'GET_BOOK');
VALUES (3, 'GET_GENRE');

